app/models/administrator.rb
db/migrate/20200702034035_create_administrators.rb
db/schema.rb
test/fixtures/administrators.yml
test/models/administrator_test.rb

Feature model/administrators

---

app/models/cart_item.rb
db/migrate/20200702030906_create_cart_items.rb
db/migrate/20200702032600_add_customer_id_to_cart_items.rb
db/migrate/20200702032950_add_item_id_id_to_cart_items.rb
db/migrate/20200702033024_add_amount_to_cart_items.rb
db/schema.rb
test/fixtures/cart_items.yml
test/models/cart_item_test.rb

cart_items

---

app/models/genre.rb
db/migrate/20200702035449_create_genres.rb
test/fixtures/genres.yml
test/models/genre_test.rb

feature-model/genres

---

app/models/order.rb
db/migrate/20200702040417_create_orders.rb
test/fixtures/orders.yml
test/models/order_test.rb

feature-model/order

---

app/models/customer.rb
db/migrate/20200702042226_create_customers.rb
test/fixtures/customers.yml
test/models/customer_test.rb

顧客モデルの追加
退会ステータス、姓（カナ）、名（カナ）、住所、姓（漢）、名（漢字）、住所、電話番号のカラムをそれぞれ追加

Feature model/customers

---

app/models/shipping.rb
db/migrate/20200702042231_create_shippings.rb
test/fixtures/shippings.yml
test/models/shipping_test.rb

feature-model/shippings

---

app/models/order_item.rb
db/migrate/20200702044506_create_order_items.rb
test/fixtures/order_items.yml
test/models/order_item_test.rb

注文商品モデルの追加
注文ID、商品ID、製作ステータス、個数、価格のカラムをそれぞれ追加

[Add]order_item model

---

app/assets/javascripts/homes.coffee
app/assets/stylesheets/homes.scss
app/controllers/homes_controller.rb
app/helpers/homes_helper.rb
test/controllers/homes_controller_test.rb

[Add]Homescontroller

---

app/assets/javascripts/admin/customers.coffee
app/assets/javascripts/admin/genres.coffee
app/assets/javascripts/admin/items.coffee
app/assets/javascripts/admin/orders.coffee
app/assets/stylesheets/admin/customers.scss
app/assets/stylesheets/admin/genres.scss
app/assets/stylesheets/admin/items.scss
app/assets/stylesheets/admin/orders.scss
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/orders_controller.rb
app/helpers/admin/customers_helper.rb
app/helpers/admin/genres_helper.rb
app/helpers/admin/items_helper.rb
app/helpers/admin/orders_helper.rb
test/controllers/admin/customers_controller_test.rb
test/controllers/admin/genres_controller_test.rb
test/controllers/admin/items_controller_test.rb
test/controllers/admin/orders_controller_test.rb

[Add]admin/controllers

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/today.html.erb
db/schema.rb

admin/orders/today
admin/orders/indexの更新

[Update]admin/orders

---

app/controllers/public/customers_controller.rb
app/views/public/customers/show.html.erb
app/views/public/customers/withdraw.html.erb
db/schema.rb

add contoroller customer

---

app/controllers/public/customers_controller.rb
app/models/customer.rb
app/models/genre.rb
app/models/item.rb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/public/customers/withdraw.html.erb

public/customer controller 作成
public/customer view 作成{
show 
edit 
withdraw}

feature-task/public/customers

---

app/controllers/admin/items_controller.rb
app/models/genre.rb
app/models/item.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

admin/items controllerに
index, new, create, edit, showアクションを定義
admin/item/new , admin/items, admin/item/;id, admin/item/:id/editページを作成。
admin/item/newページで<% f.attchment_field %>でエラーが出ています。

[Upgate]admin/items

---

app/controllers/admin/genres_controller.rb
app/models/genre.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb

admin/genre/controllerにindex, edit, createアクションを定義
admin/genres, admin/genre/:id/editページを作成

Feature tasks38 41

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb

admin/customer/controller作成
admin/customer/index, admin/customer/show, admin/customer/editページ作成

Feature tasks42 45

---

app/assets/stylesheets/application.scss
app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/controllers/public/orders_controller.rb
app/controllers/public/shippings_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/layouts/_sidebar.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/new.html.erb
config/locales/ja.yml

[Add]注文情報入力画面

---

config/routes.rb

[Update]ルーティング

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/confirm.html.erb
config/routes.rb

[Fix]ショッピングカート画面

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/orders_controller.rb
app/views/layouts/application.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/orders/confirm.html.erb
config/routes.rb

[Fix]ショッピングカート機能

---

app/controllers/public/cart_items_controller.rb

[Update]CartItemsコントローラー

---

app/controllers/admin/genres_controller.rb
app/controllers/public/orders_controller.rb
app/models/cart_item.rb
app/models/order.rb
app/views/admin/items/new.html.erb
app/views/layouts/application.html.erb
app/views/public/items/index.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/new.html.erb
config/routes.rb

Feature 10

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/public/cart_items_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb

admin関連で発生していた細かいエラーを直しました。
genre, itemを作成できるようにしました。
todayページを表示出来るようにしました
いくつかあったスペルミスを修正しました。。

[fix]admin

---

app/assets/stylesheets/application.scss
app/controllers/public/items_controller.rb
app/views/layouts/_sidebar.html.erb
app/views/layouts/application.html.erb
app/views/public/items/_sidebar.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb

商品一覧画面と商品詳細画面のジャンル検索をUpdateしました。

[Update]ジャンル検索
